[package]
name = "mkargus/parttoterrain"
version = "1.7.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
React = "jsdotlua/react@=17.2.1"
ReactRoblox = "jsdotlua/react-roblox@=17.2.1"
BasicState = "csqrl/basicstate@=0.2.6"
