[package]
name = "mkargus/parttoterrain"
version = "1.6.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
Roact = "roblox/roact@=1.4.4"
RoactHooks = "kampfkarren/roact-hooks@=0.5.1"
BasicState = "csqrl/basicstate@=0.2.6"
