[package]
name = "mkargus/parttoterrain"
version = "1.6.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
React = "jsdotlua/react@=17.1.0"
ReactRoblox = "jsdotlua/react-roblox@=17.1.0"
BasicState = "csqrl/basicstate@=0.2.6"
