[package]
name = "mkargus/parttoterrain"
version = "1.7.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
React = "haedrix/react@=17.3.8"
ReactRoblox = "haedrix/react-roblox@=17.3.8"
BasicState = "csqrl/basicstate@=0.2.6"
