name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get install luarocks
        sudo luarocks install luacheck
        sudo luarocks install luafilesystem
    - name: Run Luacheck
      run: luacheck src
