name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: CompeyDev/setup-rokit@v0.1.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Selene
      run: |
        selene generate-roblox-std
        selene ./src

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Wally packages
        run: wally install

      - name: Build plugin
        run: rojo build default.project.json -o PartToTerrain.rbxm
