name: Lint

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Selene
      run: |
        wget -q -O selene-zip https://github.com/Kampfkarren/selene/releases/download/0.9.2/selene-0.9.2-linux.zip
        unzip selene-zip
        chmod +x ./selene

    - name: Generate Roblox standards
      run: ./selene generate-roblox-std

    - name: Run Selene
      run: ./selene ./src
