name: Lint

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Selene
      run: |
        wget -q -O selene-zip https://github.com/Kampfkarren/selene/releases/download/0.14.0/selene-0.14.0-linux.zip
        unzip selene-zip -d /usr/bin && chmod +x /usr/bin/selene

    - name: Generate Roblox standards
      run: selene generate-roblox-std

    - name: Run Selene
      run: selene ./src
